# Tema 1: Herramientas python para ciencia de los datos

## Ejercicios de Numpy

In [15]:
import numpy as np

#### Ejercicio 1

Generar una matrix aleatoria 3x4 y normalizar sus componentes (trasladándolos y escalándolos) de manera que el menor sea 0 y el mayor 1.

In [41]:
A = np.random.randint(10, size=(3,4))
print(A, A.min(axis=0), A.max(axis=0))
normalice =(A - A.min()) / (A.max() - A.min())
print(normalice)

[[8 3 5 7]
 [7 3 5 9]
 [9 4 3 5]] [7 3 3 5] [9 4 5 9]
[[0.83333333 0.         0.33333333 0.66666667]
 [0.66666667 0.         0.33333333 1.        ]
 [1.         0.16666667 0.         0.33333333]]


In [ ]:
# Ejemplo:

# array original:

# array([[ 1,  4, -4, -4],
#        [ 4,  1, -5,  1],
#        [ 2, -3,  0, -4]]

# array normalizado
# array([[0.66666667, 1.        , 0.11111111, 0.11111111],
#        [1.        , 0.66666667, 0.        , 0.66666667],
#        [0.77777778, 0.22222222, 0.55555556, 0.11111111]])







#### Ejercicio 2

Construir una matriz 3x4 cuyas tres filas son los elementos del 0 al 3

In [59]:
# Matriz con ceros
B = np.zeros((3,4))
# Matriz con 4 elementos
C = np.arange(4)

print(B, C)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] [0 1 2 3]


In [ ]:
#### Ejemplo:
#array([[0., 1., 2., 3.],
#       [0., 1., 2., 3.],
#       [0., 1., 2., 3.]])



#### Ejercicio 3

En una matriz 20x20, obtener la matriz que se obtiene al extraer las filas de índice par y las columnas de índice impar.

In [60]:
# Crear un array cualquier de 400 elementos y redimencionarlos a 20x20
D=np.arange(400).reshape(20,20)
# print(D)
# Las columnas de indice par con los elementos de indice impar
D[::2,1::2]


array([[  1,   3,   5,   7,   9,  11,  13,  15,  17,  19],
       [ 41,  43,  45,  47,  49,  51,  53,  55,  57,  59],
       [ 81,  83,  85,  87,  89,  91,  93,  95,  97,  99],
       [121, 123, 125, 127, 129, 131, 133, 135, 137, 139],
       [161, 163, 165, 167, 169, 171, 173, 175, 177, 179],
       [201, 203, 205, 207, 209, 211, 213, 215, 217, 219],
       [241, 243, 245, 247, 249, 251, 253, 255, 257, 259],
       [281, 283, 285, 287, 289, 291, 293, 295, 297, 299],
       [321, 323, 325, 327, 329, 331, 333, 335, 337, 339],
       [361, 363, 365, 367, 369, 371, 373, 375, 377, 379]])

#### Ejercicio 4

Dada una matriz A de tamaño 10x4 y otra B de tamaño 10x1 con valores entre 0 y 100, devolver una matriz conteniendo las filas que corresponden a las posiciones de B que son mayores de 50 

In [65]:
# Creo matriz de 100
A=np.random.randint(100, size=(10,4))
# Creo matrz de 10
B=np.random.randint(100, size=(10,))
print(A,B)
# b>50 es booleana, luego A sera una regla sobre a regla anterior
print(A[B>50])

[[19  6 78 44]
 [ 4 26 49 93]
 [ 2 98 97 24]
 [21 64  0  0]
 [ 5 33 93 67]
 [36 51 87 17]
 [13 11 91  2]
 [46 84 71 24]
 [33 45 13 49]
 [10 80 45 83]] [ 2 41 64 23 21  2 65 18 73 89]
[[ 2 98 97 24]
 [13 11 91  2]
 [33 45 13 49]
 [10 80 45 83]]


In [ ]:
#### Ejemplo:

# Si A es:
# array([[59, 53, 45, 76],
#        [65, 43, 22, 88],
#        [29, 59,  8, 57],
#        [77, 85, 70, 48],
#        [29, 72, 35, 79],
#        [ 8, 99, 64, 76],
#        [53, 80, 50, 40],
#        [82, 99, 28, 22],
#        [10, 59, 13, 41],
#        [81, 75, 53, 75]]
#
# Y B es:
# array([14, 17, 75, 40, 86, 16, 77, 81, 77, 50]))

# Entonces se pide obtener:

#array([[29, 59,  8, 57],
#       [29, 72, 35, 79],
#       [53, 80, 50, 40],
#       [82, 99, 28, 22],
#       [10, 59, 13, 41]])




#### Ejercicio 5

Definir una función `f_1_0(n)` que recibe un número natural n y devuelve un array bidimensional de n filas y n columnas que tiene 1s en los bordes y 0s en el interior.

In [70]:
# Verlo despues
def f_1_0(dato):
    A=np.ones((dato, dato))
    A[1:-1,1:-1]=0
    return A
print(f_1_0(1))

[[1.]]


In [ ]:
# Ejemplo:

# >>> f_1_0(10)

# array([[1., 1., 1., 1., 1., 1., 1., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 0., 0., 0., 0., 0., 0., 1.],
#       [1., 1., 1., 1., 1., 1., 1., 1.]])



#### Ejercicio 6

Generar un array unidimensional, con enteros de 20 a 32, y a continuación, usando indexado, invertir el orden. 

In [ ]:
# Ejemplo:

# A partir del array([32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20]), generar:
# array([32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20])




#### Ejercicio 7

Definir una función g tal que dado un número natural n y otro entero k, obtiene un array bidimensional n x n con k (entero) en todas sus componentes 



In [71]:
# No lo hizo

[]


In [ ]:
# Ejemplo:

# >>> g(5,9)

# array([[9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9],
#        [9, 9, 9, 9, 9]], dtype=int32)



#### Ejercicio 8

Crear una matriz bidimensional 8x8 con 1s y 0s como en un tablero de ajedrez.


In [72]:
A=np.zeros((8,8), dtype = int)
# Falta el paseo por los datos
print(A)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [73]:
# Ejemplo:

# array([[1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int32)



#### Ejercicio 9

Generar una matriz 5x5 y normalizarla (restar la media y dividiendo por la desviación típica de todos los elementos). Hacerlo también normalizando cada columna por separado (restando la media y diviendo por la desviación típica de la columna en la que está el elemento).   

In [83]:
A=np.arange(25).reshape(5,5)
print(A)
# La media de cada columna dividiendo por la otra con el truco de axis
# Ver la funcion std
B=A-A.mean(axis=0)/A.std(axis=0)
print(B)
# (A - A.min()) / (A.max() - A.min())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[-1.41421356 -0.55563492  0.30294373  1.16152237  2.02010101]
 [ 3.58578644  4.44436508  5.30294373  6.16152237  7.02010101]
 [ 8.58578644  9.44436508 10.30294373 11.16152237 12.02010101]
 [13.58578644 14.44436508 15.30294373 16.16152237 17.02010101]
 [18.58578644 19.44436508 20.30294373 21.16152237 22.02010101]]


In [ ]:
# Ejemplo:

# Si A es:

# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14],
#        [15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24]])

# Entonces con la primera normalización quedaría:

# array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
#        [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
#        [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
#        [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
#        [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]]

# Y con la normalización por columnas:

# array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
#        [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
#        [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
#        [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
#        [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])



#### Ejercicio 10

Cambiar de signo todos los elementos de un array de enteros que estén entre 3 y 8.


In [ ]:
A=np.arange(12).reshape((3,4))
# No llegue a copiarlo
A[(A<=4)& A<=1]

In [ ]:
# Ejemplo:

# Si tenemos:

# array([[ 0,  1,  2, 3],
#        [ 4,  5,  6, 7],
#        [ 8,  9, 10, 11]])

# se trataría de obtener:

# array([[ 0,  1,  2, -3],
#        [-4, -5, -6, -7],
#        [-8, -9, 10, 11]])




#### Ejercicio 11

Dados dos arrays bidimensionales A y B del mismo tamaño, calcular `(A+B)*(-A/2)`, de manera que las operaciones se realicen sobre el espacio de memoria de A y B, sin generar copias.


#### Ejercicio 12

Supongamos que tenemos un array unidimensional con nombres de personas, y otro con sus respectivas edades. Usando *fancy indexing* y la función `np.argsort()`, obtener un array con los nombres ordenados de menor a mayor edad. 



In [85]:
# --- Ejemplo:
nombres=np.array(["Juan","Luis","Ramón","Ana","Fernando","Beatriz","Carmen"])
# yo puedo usar este array como indice indexado a otro array
edades=np.array([34,21,54,12,3,7,22])
nombres[edades.argsort()]
print(nombres)

# Ordenados según edad: array(['Fernando', 'Beatriz', 'Ana', 'Luis', 'Carmen', 'Juan', 'Ramón'],dtype='<U8')



['Juan' 'Luis' 'Ramón' 'Ana' 'Fernando' 'Beatriz' 'Carmen']


#### Ejercicio 13 (Sección 4.7 del libro *Python for Data Analysis*, de W. McKinney)

Un *paseo aleatorio* es una sucesión de enteros, comenzando en 0, de manera que cada uno de ellos se obtiene sumando 1 o -1 al anterior, aleatoriamente y con igual probabilidad. 

Este es el código python para generar paseos aleatorios de 100 pasos:

In [ ]:
import random
posicion = 0
paseo = [posicion]
npasos = 100
for i in range(npasos):
    paso = 1 if random.randint(0, 1) else -1
    posicion += paso
    paseo.append(posicion)
    
print(walk)

**13.1** Definer una función `paseo_aleatorio(npasos)` que genere un paseo aleatorio de `npasos`, **usando numpy** . *Indicación:* usar `np.where` y `np.cumsum`.

In [ ]:
# Ejemplo:

# >>> paseo_aleatorio(100)
# array([ 1,  0, -1, -2, -3, -4, -5, -4, -3, -2, -1, -2, -1,  0, -1, -2, -1,
#        -2, -3, -4, -5, -4, -5, -6, -5, -4, -3, -2, -1,  0, -1,  0,  1,  2,
#         3,  2,  1,  2,  3,  4,  3,  2,  3,  4,  3,  2,  3,  2,  1,  2,  1,
#         2,  1,  0,  1,  2,  3,  4,  5,  4,  3,  2,  1,  0,  1,  0, -1,  0,
#        -1,  0,  1,  2,  1,  0, -1, -2, -1, -2, -3, -2, -1,  0, -1, -2, -1,
#        -2, -1,  0, -1, -2, -3, -2, -1,  0,  1,  2,  3,  4,  3,  2])




**13.2** Calcular la posición inferior y superior por la que pasa un paseo, y el momento en el que se alcanzan.

**13.3** Generar un paseo de 1000 pasos, y calcular:

* cuántas veces se está a más de 10 pasos de distancia del origen. 
* cuál es el primer paso en el que se separa a distancia 10 del origen.